
#   python response.py --archetype 'smrf_9_ii' # works *
#   python response.py --archetype 'smrf_3_iv' # works *
#   python response.py --archetype 'smrf_6_iv' # works *
#   python response.py --archetype 'smrf_9_iv' # works *


    python response.py --archetype 'scbf_3_ii' # Segmentation fault
    python response.py --archetype 'scbf_6_ii' # ...
    python response.py --archetype 'scbf_9_ii' # ...

    python response.py --archetype 'scbf_3_iv' # ...
    python response.py --archetype 'scbf_6_iv' # ...
    python response.py --archetype 'scbf_9_iv' # ...


    python response.py --archetype 'brbf_3_ii' # ERROR Could not create uniaxialMaterial Fatigue
    python response.py --archetype 'brbf_6_ii' # ...
    python response.py --archetype 'brbf_9_ii' # ...

    python response.py --archetype 'brbf_3_iv' # ...
    python response.py --archetype 'brbf_6_iv' # ...
    python response.py --archetype 'brbf_9_iv' # ...

